### ISSUE TITLE
All websites contain the same HTML

### ISSUE THREAD

**Issue by willbishops** [fg2it/phantomjs-on-raspberry#3]
>>> from selenium import webdriver
>>> driver = webdriver.PhantomJS()
>>> driver.get('putanywebsitehere')
>>> driver.page_source
'<html><head></head><body></body></html>'

This shouldn't happen, the page_source does not contain real source code, meaning nothing else works either

**Comment by fg2it** [comment]
Did you try `phantomjs` binary directly ? How, and what, did you install ?

**Comment by fg2it** [comment]
Without update, and since I suspect it is not related to my build, I close this issue.
