### ISSUE TITLE
Does not work on Debian Stretch

### ISSUE THREAD

**Issue by ragesoss** [fg2it/phantomjs-on-raspberry#4]
Thanks for this! I got it up and running on Raspberry Pi 3 on jessie. However, after an upgrade to stretch, I get an error — `QXcbConnection: Could not connect to display` — when I run it. In retrospect, that's not surprising since your repo clearly says it's for wheezy and jessie.

Any pointers for making it work on stretch?

**Comment by fg2it** [comment]
I am not sure this is related to my build. The restriction I stated on os is more related to the libraries loaded by `phantomjs`. A quick search on the github page of the phantomjs project seems to rise some potential causes for your problem. Maybe you should look there.
A way to confirm this would be a stretch docker on your jessie raspberry. I think I tried that and that it worked. I would gladly do it myself, unfortunately, my pi are somewhere in an unlabelled box, in a new flat crowded with unlabelled boxes ...

**Comment by fg2it** [comment]
@ragesoss did you find a solution to your problem ?

**Comment by ragesoss** [comment]
@fg2it I haven't tried again yet. I did look around on the phantomjs github page and tried a few settings before, but couldn't get it working.

**Comment by fg2it** [comment]
@ragesoss Don't know where you are with this problem but I try it inside a stretch docker container. There was a mistake in the `Readme.txt` reporting a non existing dependency to `libpng12`. `phantomjs` has no such dependency, it is `libfontconfig` that depends on it on wheezy and jessie. On stretch, this version of `libpng` is replaced by `libpng16`. So, the only this to do to have it run is to remove `libpng12` from the `apt-get install` step. Other than that, is seems to work.
If you still have this problem, or if you have found a way to fix it, please report it.
